version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: post2bsky
    repository:
      owner: lCyou
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/lCyou/zenn-post2bsky"
    description: "Terminal TUI app to post to Bluesky"
    license: "MIT"
    install: |
      bin.install "post2bsky"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
